[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "geovisxrd"
version = "0.5.0"
description = "GeoVisXRD: An Open-Source Python Library for Geospatial Shapley Value Computation and Visualization"


readme = "README.md" 


authors = [
  { name = "Yuanhan Shu", email = "yuanhan.shu@tum.de" },
]


license = { text = "MIT" }


classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
]


dependencies = [
    "numpy",
    "pandas",
    "tqdm",
    "scipy",
    "shap",
    "joblib",
    "xgboost<3.0.0",
    "scikit-learn",
    "lightgbm",
    "matplotlib",

    "statsmodels", ## 2D lowess smoothing

    ## causal discovery v0.5.0
    "networkx",       # Graph structure foundation
    "torch",          # Deep learning foundation (needed for SAM, NOTEARS)
    "causal-learn",   # PC algorithm
    "lingam",         # LiNGAM algorithm
    "causalnex",      # NOTEARS algorithm
    "cdt",
]

# Python version requirement
requires-python = ">=3.8"


# # 3. 项目链接：替代 url
# [project.urls]
# Homepage = "https://github.com/Ziqi-Li/geoshapley"
# Repository = "https://github.com/Ziqi-Li/geoshapley"


# # 4. 命令行脚本：替代 entry_points
# [project.scripts]
# geovisxrd = "geovisxrd.__main__:main"